fix problems

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -11,8 +11,9 @@ jobs:
     echo-goodbye:
         runs-on: ubuntu-latest
         steps:
-            - name: |
-                echo "I will fail"
-                exit 1
+            - name: Failed step
+              run: |
+                    echo "I will fail"
+                    exit 1
             - name: Say goodbye
               run: echo "Goodbye, World!"
